# Generated by Django 5.1.4 on 2024-12-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('land_type', models.CharField(choices=[('residential', 'Жилая'), ('agricultural', 'Сельскохозяйственная'), ('commercial', 'Коммерческая')], max_length=50)),
                ('image', models.ImageField(upload_to='lands/')),
            ],
        ),
    ]
